### ISSUE TITLE
输出文章内容如何过滤

### ISSUE THREAD

**Issue by faonecze** [thinkmoon/TmWeBlog#2]
大佬，我小白。
前几天刚看到你这个项目感觉挺不错的，至少比wetypecho更适合自己使用。

前天晚上提交的也通过微信审核，可是发现自己站点后来添加的“APlayer for Typecho和JWPlayer”插件，在微信小程序上直接显示“markdown”的原信息，想把这部分信息过滤掉。昨晚看了一堆小程序教程没看明白，求指导。

aplayer显示信息如下：
`[Meting]
[Music title="对你爱不完" author="郭富城" url="//xxx/typecho/2019/12/1997001409.m4a" pic="//xxx/typecho/2019/12/278448182.jpg" /]
[/Meting]`

jwplayer显示信息如下：
`https://xxx/typecho/2018/11/326994541.mp4|
image=https://xxx/typecho/2018/11/238393382.png|
title=叶问 打十个日本人|
autostart=false|
repeat=true|
width=100%`

**Comment by thinkmoon** [comment]
晚些给你答复

**Comment by faonecze** [comment]
[求助]大佬适当的处理方法吗?

**Comment by thinkmoon** [comment]
![image](https://user-images.githubusercontent.com/28600813/70998420-4b057c00-2112-11ea-8152-3b30877855d9.png)
v0.1.6版本

**Comment by thinkmoon** [comment]
Aplayer的问题已在新版本中适配播放
