### ISSUE TITLE
请问首页文章图片不显示是什么怎么回事，

### ISSUE THREAD

**Issue by Her-soulmate** [thinkmoon/TmWeBlog#3]

**Comment by gxuzf** [comment]
修改@/static/utils/api.js 中的baseUrl后，依然调用的贵站文章，没有调用我自己的文章

**Comment by Her-soulmate** [comment]
> 修改@ / static / utils / api.js中的baseUrl后，依然调用的贵站文章，没有调用我自己的文章

全局搜索博主的域名替换成自己的域名就可以了，不止/static/utils/api.js里的一处，

**Comment by thinkmoon** [comment]
你好，请修改文件`@/common/vendor.js`,搜索`www.thinkmoon.cn`替换为你的域名。
